name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test (${{ matrix.os }}@${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        node:
          - '12'
          - '14'
          - '16'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn --frozen-lockfile
      - run: |
          rm -rf node_modules/.cache
          npm run test
          npm run bundle
